--- # BRIDGE (800, 600, 4, 4, 0.9, 5, 2, 2, null, "images/20110114/bridge.jpg", null, null, null, 1, null),
title:          Bridge

width:          800
height:         600

widthSpacing:   4
heightSpacing:  4


images:
    - name:     bridge
      file:     /Users/boxysean/Desktop/projects/fortyfive/20110114/bridge.jpg


lineA: &id001
    straightProb:  0.9
    drawSpeed:     1

    movement:
        name:          IntelligentMovement
        intelligence:  3

    draw:
        name:          ImageDraw
        image:         bridge
        strokeWidth:   2


lines:         [*id001, *id001, *id001, *id001, *id001]


