--- # DALAI (800, 600, 2, 2, 0.75, 5, 1, 2, null, "images/20110114/dalai.jpg", null, null, null, 10, null),
title:          Dalai

width:          800
height:         600

widthSpacing:   2
heightSpacing:  2

drawSpeedMultiplier:   10


images:
    - name:     dalai
      file:     /Users/boxysean/Desktop/projects/fortyfive/20110114/dalai.jpg


lineA: &id001
    straightProb:  0.75

    movement:
        name:          IntelligentMovement
        intelligence:  3
    
    draw:
        name:          ImageDraw
        image:         dalai


lines:          [*id001, *id001, *id001, *id001, *id001]

...

