--- # DANSE_BLACK_DIAG (540, 720, 1, 1, 1, 10, 1, 0, null, "images/danse-black.jpg", "02020202", null, new int[] { 10, 10 }, 10, null),

title:          Danse Black Diag

width:          540
height:         720

widthSpacing:   1
heightSpacing:  1

drawSpeedMultiplier:   10
    

images:
    - name:     danse-black
      file:     /Users/boxysean/Desktop/projects/fortyfive/danse-black.jpg
    

lineA: &id001
    straightProb:  1.0
    direction:     "02020202"
        
    movement:
        name:          IntelligentMovement
        intelligence:  3
        
    draw:
        name:          ImageDraw
        image:         danse-black

lineB: &id002
    <<: *id001
    drawSpeed:         10

lines:          [*id002, *id002, *id001, *id001, *id001, *id001, *id001, *id001, *id001, *id001]

...


