--- # EYE (180, 360, 2, 2, 1, 5, 1, 0, null, "images/eye.jpg", null, null, null, 5, null),
title:          Eye

width:          180
height:         360

widthSpacing:   2
heightSpacing:  2

drawSpeedMultiplier:   5


images:
    - name:     eye
      file:     /Users/boxysean/Desktop/projects/fortyfive/eye.jpg
      

lineA: &id001
    straightProb:  1.0
        
    movement:
        name:          IntelligentMovement
        intelligence:  1
        
    draw:
        name:          ImageDraw
        image:         eye
        
lines:          [*id001, *id001, *id001, *id001, *id001]
...

