---
title:          Mono

width:          800
height:         600

widthSpacing:   4
heightSpacing:  4


lineTop: &id001
    straightProb:  1.0
    direction:     "21000001"
    drawSpeed:     1

    movement:
        name:          IntelligentMovement
        intelligence:  1
    
    draw:
        name:          SolidDraw
        strokeWidth:   1
        red:           255

    startArea:
        name:          RectangleArea
        x:             0
        y:             0
        width:         800
        height:        5 

        
lineBottom: &id002
    <<: *id001
    direction:     "00012100"

    startArea:
        name:          RectangleArea
        x:             0
        y:             596
        width:         800
        height:        5 

 
lineLeft: &id003
    straightProb:  1.0
    drawSpeed:     1
    direction:     "00000121"
    
    movement:
        name:          IntelligentMovement
        intelligence:  1

    draw:
        name:          SolidDraw
        strokeWidth:   1
        green:         255
    
    startArea:
        name:          RectangleArea
        x:             796
        y:             0
        width:         5
        height:        600

lineRight: &id004
    <<: *id003
    direction:     "01210000"
        
    startArea:
        name:          RectangleArea
        x:             0
        y:             0
        width:         5
        height:        600


lines:          [*id001, *id002, *id003, *id004]

drawSpeedMultiplier: 20

...
