---

colours:
    - name:        red
      red:         255

    - name:        blue
      blue:        255

    - name:        green
      green:       255


colourPalettes:
    - name:        primaryColours
      mode:        linear
      colours:     [red, green, blue]

    - name:        primaryLinear1
      mode:        linear
      colours:     [red, green, blue]

    - name:        primaryLinear2
      mode:        linear
      colours:     [green, blue, red]

...
