--- # DANSE_WHITE (540, 720, 3, 3, 1, 5, 1, 2, null, "images/danse-white.jpg", null, null, null, 10, null),
title:          Danse White

width:          540
height:         720

widthSpacing:   3
heightSpacing:  3

drawSpeedMultiplier:   10


images:
    - name:     danse-white
      file:     /Users/boxysean/Desktop/projects/fortyfive/danse-white.jpg
      

lineA: &id001
    straightProb:  1.0
        
    movement:
        name:          IntelligentMovement
        intelligence:  3
        
    draw:
        name:          ImageDraw
        image:         danse-white
        
lines:          [*id001, *id001, *id001, *id001, *id001]
...
    

