---
title:          Space Jam 03

bgcolour:       black

width:          1024
height:         768

widthSpacing:   2
heightSpacing:  2


images:
    - name:     background
      file:     /Users/boxysean/Documents/workspace/Processing/images/EricBirthdayBackground.jpg

    - name:     cross
      file:     /Users/boxysean/Documents/workspace/Processing/images/EricBirthdayCross.png

    - name:     happybirthday
      file:     /Users/boxysean/Documents/workspace/Processing/images/EricHappyBirthdayThresh.png

    - name:     wood
      file:     /Users/boxysean/Documents/workspace/Processing/images/WoodGradient.png


lineA: &id001
    straightProb:  0.97
    drawSpeed:     3
    direction:     "12121212"

    draw:
        name:          ImageDraw
        image:         background
        strokeWidth:   1
        scale:         -10
        xOffset:       -1
        yOffset:       -1
        
    threshold:
        - name:        cross
          invert:      true
          scale:       1.25
          xOffset:     -1
          yOffset:     -1

        - name:        happybirthday
          invert:      true
          xOffset:     -1

    movement:
        name:          IntelligentMovement
        intelligence:  2


lineB: &id002
    <<: *id001

    movement:
        name:          ClingMovement
        intelligence:  2



lineC: &id003
    straightProb:  1
    drawSpeed:     3

    draw:
        name:          ImageDraw
        image:         wood
        strokeWidth:   1
        scale:         1.25
        xOffset:       -1
        yOffset:       -1

    threshold:
        - name:        cross
          scale:       1.25
          xOffset:     -1
          yOffset:     -1

    movement:
        name:          IntelligentMovement
        intelligence:  3

    startArea:
        name:          RectangleArea
        x:             375
        y:             160
        width:         275
        height:        455


lineD: &id004
    straightProb:  0.87
    drawSpeed:     2

    draw:
        name:          ImageDraw
        image:         wood
        strokeWidth:   1
        xOffset:       -1

    threshold:
        - name:        happybirthday
          xOffset:     -1

    movement:
        name:          IntelligentMovement
        intelligence:  3

    startArea:
        name:          RectangleArea
        x:             75
        y:             0
        width:         880
        height:        150





#lines:          [*id001, *id002, *id003]
lines:          [*id001, *id001, *id002, *id002, *id003, *id004]
...

