---
title:          Red Green

completePause:  750

includes:
    - ../configs/Colours.yaml


colourPalettes:
    - name:     flipTop
      mode:     linear
      colours:  [red, green, blue]

    - name:     flipBottom
      mode:     linear
      colours:  [red, green, blue]

    - name:     flipLeft
      mode:     linear
      colours:  [green, blue, red]

    - name:     flipRight
      mode:     linear
      colours:  [green, blue, red]



bgcolour:       black

widthSpacing:   10
heightSpacing:  10


lineTop: &id001
    straightProb:  1.0
    direction:     "21000001"
    drawSpeed:     4

    movement:
        name:          IntelligentMovement
        intelligence:  1
    
    draw:
        name:          SolidDraw
        strokeWidth:   10
        strokeCap:     project
        palette:       flipTop

    startArea:
        - addRect:     [0, 0, width, 15]

        
lineBottom: &id002
    <<: *id001
    direction:     "00012100"

    draw:
        name:          SolidDraw
        strokeWidth:   10
        strokeCap:     project
        palette:       flipBottom

    startArea:
        - addRect:     [0, -3, width, 3]

 
lineLeft: &id003
    straightProb:  1.0
    drawSpeed:     7
    direction:     "00000121"
    
    movement:
        name:          IntelligentMovement
        intelligence:  1

    draw:
        name:          SolidDraw
        strokeWidth:   10
        strokeCap:     project
        palette:       flipLeft
    
    startArea:
        - addRect:     [-3, 0, 3, height]

lineRight: &id004
    <<: *id003
    direction:     "01210000"
        
    draw:
        name:          SolidDraw
        strokeWidth:   10
        strokeCap:     project
        palette:       flipRight

    startArea:
        - addRect:     [0, 0, 15, height]


lines:          [*id001, *id002, *id003, *id004]

...
