---

completePause:  750

strokeJoin:     round
strokeCap:      round

includes:
    - ../configs/Colours.yaml




bgcolour:       black

widthSpacing:   15
heightSpacing:  15


south: &id001
    straightProb:  1
    drawSpeed:     1
    coordBag:      centre
    direction:     "20000000"

    movement:
        name:          IntelligentMovement
        intelligence:  1

    draw:
        name:          SolidDraw
        strokeWidth:   5
        palette:       primaryLinear1

east: &id002
    <<: *id001
    direction:     "00200000"

north: &id003
    <<: *id001
    direction:     "00002000"

north: &id004
    <<: *id001
    direction:     "00000020"


lines:          [*id001, *id002, *id003, *id004]

...
