--- # HEART (600, 1000, 2, 2, 0.75, 5, 1, 2, "images/20110213/heart.jpg", null, null, null, null, 10, null),
title:          Heart

bgcolour:       black

width:          1024
height:         768

widthSpacing:   5
heightSpacing:  5

drawSpeedMultiplier:   10


images:
    - name:     heart
      file:     /Users/boxysean/Desktop/projects/fortyfive/20110213/heart.jpg
      

lineA: &id001
    straightProb:  0.75
    drawSpeed:     1

    draw:
        red:           255
        blue:          255
        green:         255
        
    threshold:
        - name:        heart
#          scale:       0.5
#          invert:      true
#          xOffset:     50
#          yOffset:     50

        - name:        heart
#          scale:       0.5
#          invert:      true
          xOffset:     450
#          yOffset:     350


    movement:
        name:          IntelligentMovement
        intelligence:  3

lineC: &id003
    straightProb:  1.0
    direction:     "00200000"
    
    threshold:
        - name:        heart
          invert:      true

    movement:
#        name:          ClingMovement
        name:          IntelligentMovement
        intelligence:  3

    draw:
        name:          SolidDraw
        red:           255
        green:         127
        blue:          127

    startArea:
        name:          RectangleArea
        x:             0
        y:             0
        width:         8
        height:        1000
        coordinateBag: forward

lineD: &id004
    <<: *id003
    
    startArea:
        name:          RectangleArea
        x:             400
        y:             0
        width:         200
        height:        1000
        
lines:          [*id001, *id001, *id001, *id001, *id001, *id003, *id003, *id003, *id003, *id003]
#lines:          [*id001, *id001, *id001, *id001, *id001]
...

