finishedPause:   300
baseDir:         IdeasForTheNewCity

snapshots:
    - 300

templates:
    - BrooklynBridge.yaml
    - Cityscape.yaml
    - CrossHatch.yaml
    - Diagonal.yaml
    - DiagonalOutside.yaml
    - FancyPatches.yaml
    - Growth.yaml
    - GrowthCentre.yaml
    - GrowthDiagonals.yaml
    - GrowthIntoCentre.yaml
    - Lightbulb.yaml
    - LightningBolt.yaml
    - LionsGate.yaml
    - Mountainscape.yaml
    - ProgressBar.yaml
    - RedGreenBig.yaml
    

