---

completePause:  750

strokeCap:      project

includes:
    - ../configs/Colours.yaml


images:
    - name:     mountainscape
      file:     ../images/MountainRangeOutline.png



bgcolour:       black

widthSpacing:   10
heightSpacing:  10


bottom: &id001
    straightProb:  1
    drawSpeed:     1
    coordBag:      [0, -1]
    direction:     "00002000"

    movement:
        name:          IntelligentMovement
        intelligence:  1

    threshold:
        - name:        mountainscape
          xOffset:     -1
          yOffset:     -1
          scale:       0.8

    draw:
        name:          SolidDraw
        strokeWidth:   15
        strokeCap:     project
        palette:       primaryLinear1

    startArea:
        - addImage:    [mountainscape]

top: &id002
    <<: *id001

    direction:     "20000000"
    drawSpeed:     2
    coordBag:      [0, 1]

    threshold:
        - name:        mountainscape
          invert:      true
          xOffset:     -1
          yOffset:     -1
          scale:       0.8


    draw:
        name:          SolidDraw
        strokeWidth:   15
        strokeCap:     project
        palette:       primaryLinear2

 


lines:          [*id001, *id002]

...
