---
title:          Red Green

width:          1024
height:         768

bgcolour:       black

widthSpacing:   4
heightSpacing:  4


lineA: &id001
    straightProb:  1.0
    direction:     "02000000"
    drawSpeed:     2

    movement:
        name:          IntelligentMovement
        intelligence:  1
    
    draw:
        name:          SolidDraw
        strokeWidth:   1
        red:           255

    startArea:
        name:          RectangleArea
        width:         4
        height:        384


lineB: &id002
    <<: *id001

    startArea:
        name:          RectangleArea
        width:         512
        height:        4


lineC: &id003
    <<: *id001
    direction:     "00000200"

    startArea:
        name:          RectangleArea
        x:             1020
        y:             384
        width:         4
        height:        384


lineD: &id004
    <<: *id003

    startArea:
        name:          RectangleArea
        x:             512
        y:             764
        width:         512
        height:        4


lineE: &id005
    straightProb:  1.0
    direction:     "00000002"
    drawSpeed:     3

    movement:
        name:          IntelligentMovement
        intelligence:  1
    
    draw:
        name:          SolidDraw
        strokeWidth:   1
        green:         255

    startArea:
        name:          RectangleArea
        x:             512
        width:         512
        height:        4


lineF: &id006
    <<: *id005
    direction:     "00000002"

    startArea:
        name:          RectangleArea
        x:             1020
        width:         4
        height:        384


lineG: &id007
    <<: *id005
    direction:     "00020000"

    startArea:
        name:          RectangleArea
        y:             384
        width:         4
        height:        384


lineH: &id008
    <<: *id007
    direction:     "00020000"

    startArea:
        name:          RectangleArea
        y:             764
        width:         512
        height:        4




lines:          [*id001, *id002, *id003, *id004, *id005, *id006, *id007, *id008]

...
