---
title:          Red Green

width:          1024
height:         768

bgcolour:       black

widthSpacing:   4
heightSpacing:  4


lineTop: &id001
    straightProb:  1.0
    direction:     "21000001"
    drawSpeed:     4

    movement:
        name:          IntelligentMovement
        intelligence:  1
    
    draw:
        name:          SolidDraw
        strokeWidth:   1
        red:           255

    startArea:
        name:          RectangleArea
        height:        5 

        
lineBottom: &id002
    <<: *id001
    direction:     "00012100"

    startArea:
        name:          RectangleArea
        y:             763
        height:        5 

 
lineLeft: &id003
    straightProb:  1.0
    drawSpeed:     4
    direction:     "00000121"
    
    movement:
        name:          IntelligentMovement
        intelligence:  1

    draw:
        name:          SolidDraw
        strokeWidth:   1
        green:         255
    
    startArea:
        name:          RectangleArea
        x:             1019
        width:         5

lineRight: &id004
    <<: *id003
    direction:     "01210000"
        
    startArea:
        name:          RectangleArea
        width:         5


lines:          [*id001, *id002, *id003, *id004]

...
