---
title:          Space Jam 01

bgcolour:       black

width:          1024
height:         768

widthSpacing:   4
heightSpacing:  4

images:
    - name:     spacejam
      file:     /Users/boxysean/Documents/workspace/Processing/images/NegativeSpaceJam.png
      
    - name:     yellowpurple
      file:    /Users/boxysean/Documents/workspace/Processing/images/YellowPurpleGradient.png



lineA: &id001
    straightProb:  0.97
    drawSpeed:     7

    draw:
        name:          ImageDraw
        image:         yellowpurple
        strokeWidth:   3
        
    threshold:
        - name:        spacejam
          scale:       1.5
          xOffset:     -1
          yOffset:     -1

    movement:
        name:          IntelligentMovement
        intelligence:  3

    startArea:
        name:          RectangleArea
        x:             75
        y:             300
        width:         850
        height:        160
#        coordinateBag: forward



lineTop: &id002
    straightProb:  1.0
    direction:     "00200200"
    drawSpeed:     3
    
    threshold:
        - name:        spacejam
          scale:       1.5
          xOffset:     -1
          yOffset:     -1

    movement:
        name:          ClingMovement

    draw:
        name:          SolidDraw
        red:           200
        green:         200
        blue:          200

    startArea:
        name:          RectangleArea
        x:             0
        y:             0
        width:         1024
        height:        275


lineBottom: &id003
    <<: *id002

    startArea:
        name:          RectangleArea
        x:             0
        y:             493
        width:         1024
        height:        275

lines:          [*id001, *id002, *id003, *id002, *id003]
...

