---

completePause:  750

includes:
    - ../configs/Colours.yaml


images:
    - name:     crosshatch
      file:     ../images/CrossHatch200.png



bgcolour:       black

widthSpacing:   10
heightSpacing:  10


left: &id001
    straightProb:  1
    drawSpeed:     1
    coordBag:      [2, 0]
    direction:     "00200000"

    movement:
        name:          IntelligentMovement
        intelligence:  1

    threshold:
        - name:        crosshatch
          xOffset:     0
          yOffset:     0

        - name:        crosshatch
          xOffset:     200
          yOffset:     0

        - name:        crosshatch
          xOffset:     400
          yOffset:     0

        - name:        crosshatch
          xOffset:     600
          yOffset:     0

        - name:        crosshatch
          xOffset:     800
          yOffset:     0

        - name:        crosshatch
          xOffset:     1000
          yOffset:     0

        - name:        crosshatch
          xOffset:     1200
          yOffset:     0

        - name:        crosshatch
          xOffset:     1400
          yOffset:     0

        - name:        crosshatch
          xOffset:     0
          yOffset:     200

        - name:        crosshatch
          xOffset:     200
          yOffset:     200

        - name:        crosshatch
          xOffset:     400
          yOffset:     200

        - name:        crosshatch
          xOffset:     600
          yOffset:     200

        - name:        crosshatch
          xOffset:     800
          yOffset:     200

        - name:        crosshatch
          xOffset:     1000
          yOffset:     200

        - name:        crosshatch
          xOffset:     1200
          yOffset:     200

        - name:        crosshatch
          xOffset:     1400
          yOffset:     200

        - name:        crosshatch
          xOffset:     0
          yOffset:     400

        - name:        crosshatch
          xOffset:     200
          yOffset:     400

        - name:        crosshatch
          xOffset:     400
          yOffset:     400

        - name:        crosshatch
          xOffset:     600
          yOffset:     400

        - name:        crosshatch
          xOffset:     800
          yOffset:     400

        - name:        crosshatch
          xOffset:     1000
          yOffset:     400

        - name:        crosshatch
          xOffset:     1200
          yOffset:     400

        - name:        crosshatch
          xOffset:     1400
          yOffset:     400

        - name:        crosshatch
          xOffset:     0
          yOffset:     600

        - name:        crosshatch
          xOffset:     200
          yOffset:     600

        - name:        crosshatch
          xOffset:     400
          yOffset:     600

        - name:        crosshatch
          xOffset:     600
          yOffset:     600

        - name:        crosshatch
          xOffset:     800
          yOffset:     600

        - name:        crosshatch
          xOffset:     1000
          yOffset:     600

        - name:        crosshatch
          xOffset:     1200
          yOffset:     600

        - name:        crosshatch
          xOffset:     1400
          yOffset:     600

        - name:        crosshatch
          xOffset:     0
          yOffset:     800

        - name:        crosshatch
          xOffset:     200
          yOffset:     800

        - name:        crosshatch
          xOffset:     400
          yOffset:     800

        - name:        crosshatch
          xOffset:     600
          yOffset:     800

        - name:        crosshatch
          xOffset:     800
          yOffset:     800

        - name:        crosshatch
          xOffset:     1000
          yOffset:     800

        - name:        crosshatch
          xOffset:     1200
          yOffset:     800

        - name:        crosshatch
          xOffset:     1400
          yOffset:     800

    draw:
        name:          SolidDraw
        strokeWidth:   10
        strokeCap:     project
        palette:       primaryLinear1


right: &id002
    <<: *id001
    coordBag:   [-1, 0]
    direction:  "00000020"


top: &id003
    <<: *id001
    coordBag:   [0, 1]
    direction:  "20000000"

    draw:
        name:          SolidDraw
        strokeWidth:   10
        strokeCap:     project
        palette:       primaryLinear2

bottom: &id004
    <<: *id003
    coordBag:   [0, -1]
    direction:  "00002000"




lines:          [*id001, *id002, *id003, *id004]

...
