---

completePause:  750

includes:
    - ../configs/Colours.yaml


images:
    - name:     lightning
      file:     ../images/LightningBoltOutline.png



bgcolour:       black

widthSpacing:   10
heightSpacing:  10


left: &id001
    straightProb:  0.90
    drawSpeed:     1
    coordBag:      centre
    direction:     "10001222"

    movement:
        name:          IntelligentMovement
        intelligence:  1

    threshold:
        - name:        lightning
          xOffset:     -1
          yOffset:     -1
          scale:       1.2

    draw:
        name:          SolidDraw
        strokeWidth:   20
        palette:       primaryLinear1
        strokeCap:     round
        strokeJoin:    bevel

    startArea:
        - addImage:    [lightning]

right: &id002
    <<: *id001
    direction:     "12221000"
    coordBag:      centre

    draw:
        name:          SolidDraw
        strokeWidth:   20
        palette:       primaryLinear2
        strokeCap:     round
        strokeJoin:    bevel

 


lines:          [*id001, *id002]

...
