---

completePause:  750

strokeCap:      project

includes:
    - ../configs/Colours.yaml


images:
    - name:     lightbulb
      file:     ../images/LightbulbOutline.png



bgcolour:       black

widthSpacing:   10
heightSpacing:  10


left: &id001
    straightProb:  0.90
    drawSpeed:     1
    coordBag:      [1, 0]
    direction:     "10001222"

    movement:
        name:          IntelligentMovement
        intelligence:  1

    threshold:
        - name:        lightbulb
          xOffset:     -1
          yOffset:     -1
          scale:       1.2

    draw:
        name:          SolidDraw
        strokeWidth:   15
        palette:       primaryLinear1

    startArea:
        - addImage:    [lightbulb]

right: &id002
    <<: *id001
    direction:     "12221000"
    coordBag:      [-1, 0]

    draw:
        name:          SolidDraw
        strokeWidth:   15
        palette:       primaryLinear2

 


lines:          [*id001, *id002]

...
