---

completePause:  750

includes:
    - ../configs/Colours.yaml


images:
    - name:     bridge
      file:     ../images/LionsGate.png


bgcolour:       black

widthSpacing:   10
heightSpacing:  10


bridge: &id001
    straightProb:  0.95
    drawSpeed:     1
    coordBag:      [0, 1]
    direction:     "00200020"

    movement:
        name:          IntelligentMovement
        intelligence:  1

    threshold:
        - name:        bridge
          xOffset:     -1
          yOffset:     -1

    draw:
        name:          SolidDraw
        strokeWidth:   20
        strokeCap:     round
        palette:       primaryLinear1

    startArea:
        - addImage:    [bridge]


background: &id002
    <<: *id001
    direction:     "02020202"
    coordBag:      [1, 2]

    threshold:
        - name:        bridge
          invert:      true
          xOffset:     -1
          yOffset:     -1

    draw:
        name:          SolidDraw
        strokeWidth:   5
        strokeCap:     round
        strokeJoin:    miter
        palette:       primaryLinear2

    startArea:
        - addRect:     [0, 0, width, height]
        - removeImage: [bridge]


lines:          [*id001, *id002]

...
