---
title:          Mono

bgcolour:       black

widthSpacing:   5
heightSpacing:  5


lineLeftBlue: &id001
    straightProb:  0.97
    drawSpeed:     2
    direction:     "02220000"
    
    movement:
        name:          ClingMovement
        intelligence:  3

    draw:
        name:          SolidDraw
        strokeWidth:   1
        green:         255
    
    startArea:
        - addRect:     [0, 0, 80, height]


lineLeftGreen: &id002
    <<: *id001
    direction:         "01210000"

    movement:
        name:          ClingMovement

    draw:
        name:          SolidDraw
        strokeWidth:   1
        blue:          255


lines:          [*id001, *id002, *id001, *id002]

...
