---
title:          Mono

bgcolour:       black

widthSpacing:   5
heightSpacing:  5


lineLeftBlue: &id001
    straightProb:  0.97
    drawSpeed:     2
    direction:     "22000002"
    
    movement:
        name:          IntelligentMovement
        intelligence:  3

    draw:
        name:          SolidDraw
        strokeWidth:   1
        green:         255
    
    startArea:
        - addRect:     [0, 0, width, 80]


lineLeftGreen: &id002
    <<: *id001

    draw:
        name:          SolidDraw
        strokeWidth:   1
        blue:          255


lines:          [*id001, *id002, *id001, *id002]

...
