---
title:          Red Green

bgcolour:       black

widthSpacing:   4
heightSpacing:  4


lineA: &id001
    straightProb:  1.0
    direction:     "02000000"
    drawSpeed:     2

    movement:
        name:          IntelligentMovement
        intelligence:  1
    
    draw:
        name:          SolidDraw
        strokeWidth:   1
        red:           255

    startArea:
        - addRect:     [0, 0, 4, /2]


lineB: &id002
    <<: *id001

    startArea:
        - addRect:     [0, 0, /2, 4]


lineC: &id003
    <<: *id001
    direction:     "00000200"

    startArea:
        - addRect:     [-4, /2, 4, /2]


lineD: &id004
    <<: *id003

    startArea:
        - addRect:     [/2, -4, /2, 4]


lineE: &id005
    straightProb:  1.0
    direction:     "00000002"
    drawSpeed:     3

    movement:
        name:          IntelligentMovement
        intelligence:  1
    
    draw:
        name:          SolidDraw
        strokeWidth:   1
        green:         255

    startArea:
        - addRect:     [/2, 0 /2, 4]


lineF: &id006
    <<: *id005
    direction:     "00000002"

    startArea:
        - addRect:     [-4, 0 4, /2]


lineG: &id007
    <<: *id005
    direction:     "00020000"

    startArea:
        - addRect:     [0, /2, 4, /2]


lineH: &id008
    <<: *id007
    direction:     "00020000"

    startArea:
        - addRect:     [0, -4, /2, 4]




lines:          [*id001, *id002, *id003, *id004, *id005, *id006, *id007, *id008]

...
