---
title:          Space Jam 01

bgcolour:       black

width:          1024
height:         768

widthSpacing:   4
heightSpacing:  4

images:
    - name:     spacejam
      file:     /Users/boxysean/Documents/workspace/Processing/images/NegativeSpaceJam.png
      
    - name:     yellowpurple
      file:    /Users/boxysean/Documents/workspace/Processing/images/YellowPurpleGradient.png



lineA: &id001
    straightProb:  0.97
    drawSpeed:     7

    draw:
        name:          ImageDraw
        image:         yellowpurple
        strokeWidth:   3
        
    threshold:
        - name:        spacejam
          scale:       1.5
          xOffset:     -1
          yOffset:     -1

    movement:
        name:          IntelligentMovement
        intelligence:  3

    startArea:
        - addImage:    [spacejam, 20, 20, 20, 10]


lineTop: &id002
    straightProb:  1.0
    direction:     "00200200"
    drawSpeed:     3
    
    threshold:
        - name:        spacejam
          scale:       1.5
          xOffset:     -1
          yOffset:     -1

    movement:
        name:          ClingMovement

    draw:
        name:          SolidDraw
        red:           200
        green:         200
        blue:          200

    startArea:
        - addRect:     [0, 0, width, height]
        - removeImage: [spacejam, 20, 20, 20, 10]


lines:          [*id001, *id002, *id002, *id002, *id002]
...

